### ISSUE TITLE
In der Thread Ansicht -> Nachrichten schreiben

### ISSUE THREAD

**Issue by MagicM-96** [EMBaudert/DatForum#64]

**Comment by Ruudii8** [comment]
was genau meinst damit?

**Comment by MagicM-96** [comment]
Dass man nicht auf das Profil gehen muss um ne Nachricht zu schicken, sondern direkt vom Beitrag aus schicken kann... hatten wir mal überlegt

**Comment by Ruudii8** [comment]
ok, mach ich rein

**Comment by Ruudii8** [comment]
done
